// <auto-generated />
namespace ManageCaseFour.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addedusercasemanytomanyrelation : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addedusercasemanytomanyrelation));
        
        string IMigrationMetadata.Id
        {
            get { return "201611092132280_added user case many to many relation"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
