// <auto-generated />
namespace ManageCaseFour.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class removedocrIdasforeignkeyfromRecords : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(removedocrIdasforeignkeyfromRecords));
        
        string IMigrationMetadata.Id
        {
            get { return "201611040333388_removed ocrId as foreign key from Records"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
