// <auto-generated />
namespace ManageCaseFour.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addedClientclassPatientProfileclass : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addedClientclassPatientProfileclass));
        
        string IMigrationMetadata.Id
        {
            get { return "201610281938427_added Client class, PatientProfile class"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
